name: Manual Test Add Subscriber

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to subscribe'
        required: true
        default: 'example@example.com'

jobs:
  test:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call Add Subscriber API
        run: |
          echo "Subscribing email: ${{ github.event.inputs.email }}"
          curl -X POST "http://localhost:3000/api/addSubscriber" \
            -H "Content-Type: application/json" \
            -d '{"email": "${{ github.event.inputs.email }}"}'
