name: Add Subscribers

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to subscribe'
        required: true
        default: 'example@example.com'

jobs:
  subscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "GIST_ID=${{ secrets.GIST_ID }}" >> $GITHUB_ENV
          echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> $GITHUB_ENV

      - name: Add new subscriber
        run: |
          email="${{ github.event.inputs.email }}"

          # Fetch the existing Gist content
          gist_response=$(curl -s -X GET "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json")

          # Extract the current email list
          if [[ $(echo "$gist_response" | jq -r '.files["subscribers.json"] | .content // empty') == "" ]]; then
            echo "subscribers.json not found or is empty."
            email_list="[]"
          else
            email_list=$(echo "$gist_response" | jq -r '.files["subscribers.json"].content | fromjson | .emailList')
          fi

          # Convert existing email list to an array
          email_array=($(echo "$email_list" | jq -r '.[]'))

          # Check if the email already exists
          if [[ " ${email_array[@]} " =~ " $email " ]]; then
            echo "Email already exists in the notification list."
            exit 1
          fi

          # Add the new email to the list
          updated_email_list=$(echo "${email_array[@]}" | jq -R . | jq -s . | jq --arg email "$email" '. += [$email]')

          # Prepare the JSON payload for updating the Gist in the desired format
          payload=$(jq -n --argjson list "$updated_email_list" '{ emailList: $list }')

          # Update Gist with new list
          response=$(curl -s -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "{\"files\": {\"subscribers.json\": {\"content\": $payload}}}")

          echo "$response"
          echo "Thank you for subscribing!"
